### ISSUE TITLE
This is just confusing, you would think I'm in the details panel, but nope, I'm in the Preview Scene Setting. Pls fix

### ISSUE THREAD

**Issue by stardast132** [hugoattal/DarkerNodes#133]
![image](https://user-images.githubusercontent.com/75868062/107267657-d45dc900-6a0c-11eb-8d51-eddcebe8542b.png)

**Comment by TheHerobrine** [comment]
Ok, this was a rejected feature, but I can make a switch to have all the panels the color of the details tab so that it'll be less confusing (cf https://github.com/TheHerobrine/DarkerNodes/issues/100)

But, again, there's no silver bullet, and it will impact ALL the tabs as they're using the same color 😅 (it's hard-coded on the engine)

**Comment by stardast132** [comment]
> Ok, this was a rejected feature, but I can make a switch to have all the panels the color of the details tab so that it'll be less confusing (cf #100)
> 
> But, again, there's no silver bullet, and it will impact ALL the tabs as they're using the same color 😅 (it's hard-coded on the engine)

Oh snap

**Comment by Zaltrip** [comment]
Not sure if this is the same feature. But in my own plugin I changed so details panels and such are the lighter color instead of using the main dark color as the rest of the windows (more like the original engine color scheme). It was just really difficult for me to see anything when the details panel blended into the main window, so adding that as toggle or a color option could be a neat feature for more users I suspect.
![image](https://user-images.githubusercontent.com/8560261/107762809-dfc33400-6d2d-11eb-80f3-cb16d96e5c1c.png)

**Comment by TheHerobrine** [comment]
@Zaltrip Yes, I think I'll do it, it's just that I don't like that it affects this color:
![image](https://user-images.githubusercontent.com/4563971/107763260-a0e1ae00-6d2e-11eb-8f36-d7ffffd3a7ce.png)

I'll find a solution 🤔 ... (Kudos for modifying the plugin yourself :D !)

**Comment by hugoattal** [comment]
Fix on UE5
