### ISSUE TITLE
Unreal Engine 5 Support for Blueprint Editor

### ISSUE THREAD

**Issue by cascade-interactive** [hugoattal/DarkerNodes#152]
Short question: What are you going to do with Darker Nodes after UE5 releases stable?

**Comment by cascade-interactive** [comment]
Short question: What are you going to do with Darker Nodes after UE5 releases stable?

**Comment by hugoattal** [comment]
@cascade-interactive 

(I deleted your duplicated comment)

Well, to be fair, Darker Nodes is less relevant in UE5 since there's already a customization system implemented. But:
- Blueprints are still using the old style
- Customization system is less intuitive than Darker Nodes (there's a lot of color to manually change)
- Darker Nodes still introduce some other customizations (paddings, fonts...)

So I think I'll still make it available in UE5, with some changes to the features, and orient it a bit more toward Blueprints customization.

**Comment by cascade-interactive** [comment]
Good to hear you'll keep supporting it.  Don't you think that the BP Editor is gonna get a visual upgrade too? I mean it's still a preview

**Comment by hugoattal** [comment]
> Don't you think that the BP Editor is gonna get a visual upgrade too? I mean it's still a preview

Yes, I thought about it, I honestly don't know. My plan right now is to continue the support and adapt the plugin toward more relevant features for UE5. But I probably won't start working on it before UE5 is out of preview.

**Comment by hugoattal** [comment]
Ready for V3 !

![image](https://user-images.githubusercontent.com/4563971/161872904-e7be71e3-d151-4d41-8fc7-f18bc3353b81.png)
