### ISSUE TITLE
Missing Icons / Text while saving  viewport layout .

### ISSUE THREAD

**Issue by FAKlR** [hugoattal/DarkerNodes#154]
Im on Ue4.26 using tiny icons

With Darker Node ON
![With DarkerNodes Active](https://user-images.githubusercontent.com/20428419/121488213-2884b400-c9d3-11eb-9bfa-90ae4508c9e8.png)

With Darker Node OFF
![With Darker Nodes Off](https://user-images.githubusercontent.com/20428419/121489224-2e2ec980-c9d4-11eb-9755-4db857c68f03.png)

**Comment by hugoattal** [comment]
Sorry for this... could you please tell me how I can reproduce by displaying this window?

**Comment by FAKlR** [comment]
> Sorry for this... could you please tell me how I can reproduce by displaying this window?

Sorry for the long answer delays !

You have to go in Window > SaveLayout >SaveLayout As .
And im using tiny Icons .

**Comment by FAKlR** [comment]
the issue is still present : (

**Comment by hugoattal** [comment]
Aaaah, sorry, I was waiting for a bit more thing to make an update, and then kindda forget about it...

I will fix it this week!

**Comment by hugoattal** [comment]
I'm stupid, I have already seen that bug here... https://github.com/hugoattal/DarkerNodes/issues/113

It should be fixable by settings the button padding to "none": https://github.com/hugoattal/DarkerNodes/issues/122#issuecomment-774516370

Though, if you're the 3rd one to report that kind of bug, I'll try to make this work for any padding (but as far as I remember, I'm not 100% sure it was actually possible...). I'll keep you up with my findings!

**Comment by FAKlR** [comment]
![image](https://user-images.githubusercontent.com/20428419/131375100-47f776b3-0ba4-457d-896c-f2a50f2a4ad1.png)

i tried your solutions it fix the invisible button text . The text is a bit off and the black square on the top right corner is still present .

Thx for keeping me in touch <3

**Comment by hugoattal** [comment]
This bug does not exist anymore in 3.0
